name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types: [closed]
  workflow_dispatch:
jobs: 
  Explore-GitHub-Actions:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    env:
          LABSUSER: ${{ secrets.MATT_LABSUSER3 }}
    steps:
      - name: Spin up EC2 Instance
        run: |
          ssh -i ${{ env.LABSUSER }} ec2-user@34.224.26.67 "bash ./redeploy.sh"
