name: Redeploy on a Merge
run-name: ${{ github.actor }} is redeploying 🚀
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types: [closed]
  workflow_dispatch:
jobs: 
  Redeploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v3
            # Make sure the @v0.7.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.MATT_LABSUSER2 }}
      - name: Spin up EC2 Instance
        shell: bash
        run: |
          ssh -i "$ssh-private-key" ec2-user@3.95.38.95 "bash ./redeploy.sh"
