name: Redeploy on a Merge
run-name: ${{ github.actor }} is redeploying 🚀
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types: [closed]
  workflow_dispatch:
jobs: 
  Redeploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    env:
        super_secret: ${{secrets.MATT_LABSUSER2 }}
    steps: 
      - name: Spin up EC2 Instance
        shell: bash
        if: ${{ env.super_secret != '' }}
        run: |
          ssh -i "$super_secret" ec2-user@34.224.26.67 "bash ./redeploy.sh"
