name: Redeploy on a Merge
run-name: ${{ github.actor }} is redeploying 🚀
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types: [closed]
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write
  
jobs: 
  Redeploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:      
      - name: Spin up EC2 Instance
        run: |
          mkdir -p ~/.ssh/
          echo "$ssh-private-key" > ~/.ssh/github-actions-key
          chmod +x ~/.ssh/github-actions-key
          ssh -i ~/.ssh/github-actions-key ec2-user@3.95.38.95 "bash ./redeploy.sh"
        env:
          ssh-private-key: ${{ secrets.MATT_LABSUSER2 }}
