name: Redeploy on a Merge
run-name: ${{ github.actor }} is redeploying 🚀
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  
env:
  INSTANCE_IP: "3.95.38.95"
  USER: "ec2-user"
  
permissions:
  contents: read
  id-token: write
  
jobs: 
  Redeploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:      
      - name: Spin up EC2 Instance
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod +x ~/.ssh/github-actions-key
          ssh -i ~/.ssh/github-actions-key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "bash ./redeploy.sh"
        env:
          SSH_HOST: ${{ env.INSTANCE_IP }}
          SSH_USER: ${{ env.USER }}
          SSH_KEY: ${{ secrets.MATT_LABSUSER2 }} 
